// Dev-only fixture generator for `just board`. Writes fictional opportunity.md files
// covering every board state so the TUI's columns, tags, and completed/ split can all
// be eyeballed without real application data. Every seeded directory name starts with
// `seed-`, which .gitignore excludes wholesale — `bun src/dev-seed-board.ts --clean`
// (or `just board-seed-clean`) removes them by the same prefix.

import { existsSync, mkdirSync, rmSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { repoRoot } from "./tui/data.ts";

interface Seed {
  kind: "applications" | "grants";
  completed: boolean;
  dir: string;
  slug: string;
  title: string;
  status: string;
  date: string;
  note: string;
}

const SEEDS: Seed[] = [
  {
    kind: "applications",
    completed: false,
    dir: "2026-06-seed-acme",
    slug: "Acme",
    title: "Acme Corp — Staff Engineer",
    status: "open",
    date: "2026-06-01",
    note: "drafting — resume not started",
  },
  {
    kind: "applications",
    completed: false,
    dir: "2026-07-seed-globex",
    slug: "Globex",
    title: "Globex — Platform Engineer",
    status: "open",
    date: "2026-07-10",
    note: "waiting on referral intro before drafting",
  },
  {
    kind: "applications",
    completed: false,
    dir: "2026-05-seed-initech",
    slug: "Initech",
    title: "Initech — Backend Engineer",
    status: "submitted",
    date: "2026-05-20",
    note: "via referral; awaiting confirmation it was filed",
  },
  {
    kind: "applications",
    completed: false,
    dir: "2026-06-seed-umbrella",
    slug: "Umbrella",
    title: "Umbrella Systems — Senior SRE",
    status: "submitted",
    date: "2026-06-15",
    note: "cold application, no referral",
  },
  {
    kind: "applications",
    completed: false,
    dir: "2026-04-seed-hooli",
    slug: "Hooli",
    title: "Hooli — Infrastructure Engineer",
    status: "interviewing",
    date: "2026-07-02",
    note: "onsite loop scheduled",
  },
  {
    kind: "grants",
    completed: false,
    dir: "2026-08-seed-opengrant",
    slug: "OpenGrant",
    title: "Open Source Sustainability Fund",
    status: "interviewing",
    date: "2026-07-25",
    note: "jury review in progress",
  },
  {
    kind: "applications",
    completed: true,
    dir: "2025-11-seed-wonderland",
    slug: "Wonderland",
    title: "Wonderland Labs — Principal Engineer",
    status: "closed - won",
    date: "2026-01-10",
    note: "offer accepted",
  },
  {
    kind: "applications",
    completed: true,
    dir: "2025-12-seed-vandelay",
    slug: "Vandelay",
    title: "Vandelay Industries — Import/Export Engineer",
    status: "closed - lost",
    date: "2026-02-14",
    note: "rejected after final round",
  },
  {
    kind: "applications",
    completed: true,
    dir: "2026-01-seed-stark",
    slug: "Stark",
    title: "Stark Industries — Site Reliability Engineer",
    status: "closed - declined",
    date: "2026-02-01",
    note: "withdrew after comp discussion",
  },
  {
    kind: "grants",
    completed: true,
    dir: "2025-10-seed-wayne",
    slug: "Wayne",
    title: "Wayne Foundation — Civic Tech Grant",
    status: "closed - lapsed",
    date: "2026-01-05",
    note: "never heard back",
  },
];

function opportunityMd(seed: Seed): string {
  return `# ${seed.title}

**Status:** ${seed.status}, ${seed.date} (${seed.note})

Fictional seed data generated by \`src/dev-seed-board.ts\` for exercising \`just board\`.
Not a real opportunity — safe to delete, and never committed (see .gitignore).

## The role

- **Posting:** fictional, seeded for TUI testing only.
- **Comp:** n/a.
- **Location:** n/a.
- **Referral:** n/a.

## Open actions

None — this is seed data, not a live application.
`;
}

// A minimal resume so `just compile`/the board's `c` key has something to find —
// `just _resolve` only matches a file with `Resume` in its name (see justfile), so a
// seeded directory with just opportunity.md fails compile with a confusing error.
function resumeTyp(s: Seed): string {
  const templatePath = s.completed ? "../../../template.typ" : "../../template.typ";
  return `#import "${templatePath}": *

#show: resume.with(
  name: "Seed Person",
  credentials: "B.Sc. Computer Science",
  title: "${s.title}",
  location: "Remote",
  email: "seed@example.com",
  phone: "(555) 010-0000",
  links: (),
)

#section("Summary")
#par[
Fictional seed resume from \`src/dev-seed-board.ts\`, so \`just compile\`/the board's
compile key has something to find. Not a real resume.
]
`;
}

function seed(root: string): void {
  for (const s of SEEDS) {
    const base = join(root, s.kind, s.completed ? "completed" : "");
    const dir = join(base, s.dir);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "opportunity.md"), opportunityMd(s));
    writeFileSync(join(dir, `Seed_Person_Resume_${s.slug}.typ`), resumeTyp(s));
  }
  console.log(`Seeded ${SEEDS.length} fictional opportunities under applications/ and grants/.`);
  console.log("Run `just board` to view them; `just board-seed-clean` to remove them.");
}

function clean(root: string): void {
  let removed = 0;
  for (const kind of ["applications", "grants"]) {
    for (const sub of [join(root, kind), join(root, kind, "completed")]) {
      if (!existsSync(sub) || !statSync(sub).isDirectory()) continue;
      for (const entry of readdirSync(sub)) {
        if (!entry.startsWith("seed-") && !/^\d{4}-\d{2}-seed-/.test(entry)) continue;
        rmSync(join(sub, entry), { recursive: true, force: true });
        removed++;
      }
    }
  }
  console.log(`Removed ${removed} seeded director${removed === 1 ? "y" : "ies"}.`);
}

const root = repoRoot();
if (process.argv.includes("--clean")) {
  clean(root);
} else {
  seed(root);
}
